twig:
    default_path: '%kernel.project_dir%/templates'
    # Thème de formulaire Bootstrap
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        paths:
            # Configuration de l'affichage Twig pour KnpPAginator
            '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
